using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace GestaoOS.WinForms
{
    public partial class OrdemServicoForm
    {
        private IContainer components = null;
        private TableLayoutPanel _root;
        private GroupBox _filtrosGroup;
        private TableLayoutPanel _filtrosLayout;
        private TableLayoutPanel _pagerLayout;
        private GroupBox _gridGroup;
        private TableLayoutPanel _editorRoot;
        private GroupBox _dadosGroup;
        private TableLayoutPanel _dadosPanel;
        private FlowLayoutPanel _salvarPanel;
        private GroupBox _itensGroup;
        private TableLayoutPanel _itensPanel;
        private TableLayoutPanel _itensTopo;
        private Label _clienteFiltroLabel;
        private Label _statusFiltroLabel;
        private Label _clienteLabel;
        private Label _aberturaLabel;
        private Label _statusLabel;
        private Label _conclusaoLabel;
        private Label _observacaoLabel;
        private Label _servicoLabel;
        private Label _quantidadeLabel;
        private Button _pesquisarButton;
        private Button _novaButton;
        private Button _anteriorButton;
        private Button _proximaButton;
        private Button _salvarButton;
        private ComboBox _filtroCliente;
        private ComboBox _filtroStatus;
        private DateTimePicker _dataInicio;
        private DateTimePicker _dataFim;
        private CheckBox _usarPeriodo;
        private DataGridView _grid;
        private Label _paginaLabel;
        private ComboBox _cliente;
        private ComboBox _status;
        private DateTimePicker _abertura;
        private DateTimePicker _conclusao;
        private CheckBox _usarConclusao;
        private TextBox _observacao;
        private ComboBox _servicoItem;
        private NumericUpDown _quantidade;
        private DataGridView _itensGrid;
        private Button _adicionarItemButton;
        private Button _removerItemButton;
        private DataGridViewTextBoxColumn _osColumn;
        private DataGridViewTextBoxColumn _clienteNomeColumn;
        private DataGridViewTextBoxColumn _aberturaColumn;
        private DataGridViewTextBoxColumn _conclusaoColumn;
        private DataGridViewTextBoxColumn _statusColumn;
        private DataGridViewTextBoxColumn _totalColumn;
        private DataGridViewTextBoxColumn _versaoColumn;
        private DataGridViewTextBoxColumn _itemServicoColumn;
        private DataGridViewTextBoxColumn _itemQuantidadeColumn;
        private DataGridViewTextBoxColumn _itemValorUnitarioColumn;
        private DataGridViewTextBoxColumn _itemImpostoColumn;
        private DataGridViewTextBoxColumn _itemTotalColumn;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            _root = new TableLayoutPanel();
            _filtrosGroup = new GroupBox();
            _filtrosLayout = new TableLayoutPanel();
            _pagerLayout = new TableLayoutPanel();
            _gridGroup = new GroupBox();
            _editorRoot = new TableLayoutPanel();
            _dadosGroup = new GroupBox();
            _dadosPanel = new TableLayoutPanel();
            _salvarPanel = new FlowLayoutPanel();
            _itensGroup = new GroupBox();
            _itensPanel = new TableLayoutPanel();
            _itensTopo = new TableLayoutPanel();
            _clienteFiltroLabel = new Label();
            _statusFiltroLabel = new Label();
            _clienteLabel = new Label();
            _aberturaLabel = new Label();
            _statusLabel = new Label();
            _conclusaoLabel = new Label();
            _observacaoLabel = new Label();
            _servicoLabel = new Label();
            _quantidadeLabel = new Label();
            _pesquisarButton = new Button();
            _novaButton = new Button();
            _anteriorButton = new Button();
            _proximaButton = new Button();
            _salvarButton = new Button();
            _filtroCliente = new ComboBox();
            _filtroStatus = new ComboBox();
            _dataInicio = new DateTimePicker();
            _dataFim = new DateTimePicker();
            _usarPeriodo = new CheckBox();
            _grid = new DataGridView();
            _paginaLabel = new Label();
            _cliente = new ComboBox();
            _status = new ComboBox();
            _abertura = new DateTimePicker();
            _conclusao = new DateTimePicker();
            _usarConclusao = new CheckBox();
            _observacao = new TextBox();
            _servicoItem = new ComboBox();
            _quantidade = new NumericUpDown();
            _itensGrid = new DataGridView();
            _adicionarItemButton = new Button();
            _removerItemButton = new Button();
            _osColumn = new DataGridViewTextBoxColumn();
            _clienteNomeColumn = new DataGridViewTextBoxColumn();
            _aberturaColumn = new DataGridViewTextBoxColumn();
            _conclusaoColumn = new DataGridViewTextBoxColumn();
            _statusColumn = new DataGridViewTextBoxColumn();
            _totalColumn = new DataGridViewTextBoxColumn();
            _versaoColumn = new DataGridViewTextBoxColumn();
            _itemServicoColumn = new DataGridViewTextBoxColumn();
            _itemQuantidadeColumn = new DataGridViewTextBoxColumn();
            _itemValorUnitarioColumn = new DataGridViewTextBoxColumn();
            _itemImpostoColumn = new DataGridViewTextBoxColumn();
            _itemTotalColumn = new DataGridViewTextBoxColumn();
            ((ISupportInitialize)_grid).BeginInit();
            ((ISupportInitialize)_quantidade).BeginInit();
            ((ISupportInitialize)_itensGrid).BeginInit();
            SuspendLayout();

            Text = "Ordens de Servico";
            StartPosition = FormStartPosition.CenterParent;
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
            BackColor = Color.FromArgb(245, 246, 248);
            Size = new Size(1280, 820);
            MinimumSize = new Size(1120, 720);
            Padding = new Padding(10);

            _root.Name = "_root";
            _root.Dock = DockStyle.Fill;
            _root.ColumnCount = 1;
            _root.RowCount = 3;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 130));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 44));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 56));

            _filtrosGroup.Name = "_filtrosGroup";
            _filtrosGroup.Text = "Pesquisa";
            _filtrosGroup.Dock = DockStyle.Fill;
            _filtrosGroup.BackColor = Color.White;
            _filtrosGroup.Padding = new Padding(10, 8, 10, 10);
            _filtrosLayout.Name = "_filtrosLayout";
            _filtrosLayout.Dock = DockStyle.Fill;
            _filtrosLayout.ColumnCount = 10;
            _filtrosLayout.RowCount = 2;
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 92));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 132));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 132));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 62));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 62));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 108));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 4));
            _filtrosLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40));
            _filtrosLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));

            _usarPeriodo.Name = "_usarPeriodo";
            _usarPeriodo.Text = "Periodo";
            _usarPeriodo.Dock = DockStyle.Fill;
            _usarPeriodo.CheckedChanged += UsarPeriodo_CheckedChanged;
            _dataInicio.Name = "_dataInicio";
            _dataInicio.Dock = DockStyle.Fill;
            _dataInicio.Margin = new Padding(3, 3, 8, 3);
            _dataInicio.Format = DateTimePickerFormat.Short;
            _dataFim.Name = "_dataFim";
            _dataFim.Dock = DockStyle.Fill;
            _dataFim.Margin = new Padding(3, 3, 8, 3);
            _dataFim.Format = DateTimePickerFormat.Short;
            _clienteFiltroLabel.Name = "_clienteFiltroLabel";
            _clienteFiltroLabel.Text = "Cliente";
            _clienteFiltroLabel.Dock = DockStyle.Fill;
            _clienteFiltroLabel.TextAlign = ContentAlignment.MiddleLeft;
            _clienteFiltroLabel.Margin = new Padding(3, 3, 6, 3);
            _filtroCliente.Name = "_filtroCliente";
            _filtroCliente.Dock = DockStyle.Fill;
            _filtroCliente.Margin = new Padding(3, 3, 8, 3);
            _filtroCliente.DropDownStyle = ComboBoxStyle.DropDownList;
            _statusFiltroLabel.Name = "_statusFiltroLabel";
            _statusFiltroLabel.Text = "Status";
            _statusFiltroLabel.Dock = DockStyle.Fill;
            _statusFiltroLabel.TextAlign = ContentAlignment.MiddleLeft;
            _statusFiltroLabel.Margin = new Padding(3, 3, 6, 3);
            _filtroStatus.Name = "_filtroStatus";
            _filtroStatus.Dock = DockStyle.Fill;
            _filtroStatus.Margin = new Padding(3, 3, 8, 3);
            _filtroStatus.DropDownStyle = ComboBoxStyle.DropDownList;
            _pesquisarButton.Name = "_pesquisarButton";
            _pesquisarButton.Text = "Pesquisar";
            _pesquisarButton.Width = 96;
            _pesquisarButton.Height = 30;
            _pesquisarButton.Margin = new Padding(4);
            _pesquisarButton.FlatStyle = FlatStyle.System;
            _pesquisarButton.UseVisualStyleBackColor = true;
            _pesquisarButton.Click += PesquisarButton_Click;
            _novaButton.Name = "_novaButton";
            _novaButton.Text = "Nova";
            _novaButton.Width = 96;
            _novaButton.Height = 30;
            _novaButton.Margin = new Padding(4);
            _novaButton.FlatStyle = FlatStyle.System;
            _novaButton.UseVisualStyleBackColor = true;
            _novaButton.Click += NovaButton_Click;
            _pagerLayout.Name = "_pagerLayout";
            _pagerLayout.Dock = DockStyle.Fill;
            _pagerLayout.ColumnCount = 3;
            _pagerLayout.RowCount = 1;
            _pagerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _pagerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96));
            _pagerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96));
            _paginaLabel.Name = "_paginaLabel";
            _paginaLabel.Dock = DockStyle.Fill;
            _paginaLabel.TextAlign = ContentAlignment.MiddleRight;
            _anteriorButton.Name = "_anteriorButton";
            _anteriorButton.Text = "Anterior";
            _anteriorButton.Width = 96;
            _anteriorButton.Height = 30;
            _anteriorButton.Margin = new Padding(4, 2, 4, 8);
            _anteriorButton.FlatStyle = FlatStyle.System;
            _anteriorButton.UseVisualStyleBackColor = true;
            _anteriorButton.Click += AnteriorButton_Click;
            _proximaButton.Name = "_proximaButton";
            _proximaButton.Text = "Proxima";
            _proximaButton.Width = 96;
            _proximaButton.Height = 30;
            _proximaButton.Margin = new Padding(4, 2, 4, 8);
            _proximaButton.FlatStyle = FlatStyle.System;
            _proximaButton.UseVisualStyleBackColor = true;
            _proximaButton.Click += ProximaButton_Click;
            _pagerLayout.Controls.Add(_paginaLabel, 0, 0);
            _pagerLayout.Controls.Add(_anteriorButton, 1, 0);
            _pagerLayout.Controls.Add(_proximaButton, 2, 0);
            _filtrosLayout.Controls.Add(_usarPeriodo, 0, 0);
            _filtrosLayout.Controls.Add(_dataInicio, 1, 0);
            _filtrosLayout.Controls.Add(_dataFim, 2, 0);
            _filtrosLayout.Controls.Add(_clienteFiltroLabel, 3, 0);
            _filtrosLayout.Controls.Add(_filtroCliente, 4, 0);
            _filtrosLayout.Controls.Add(_statusFiltroLabel, 5, 0);
            _filtrosLayout.Controls.Add(_filtroStatus, 6, 0);
            _filtrosLayout.Controls.Add(_pesquisarButton, 7, 0);
            _filtrosLayout.Controls.Add(_novaButton, 8, 0);
            _filtrosLayout.Controls.Add(_pagerLayout, 0, 1);
            _filtrosLayout.SetColumnSpan(_pagerLayout, 10);
            _filtrosGroup.Controls.Add(_filtrosLayout);

            _gridGroup.Name = "_gridGroup";
            _gridGroup.Text = "Ordens cadastradas";
            _gridGroup.Dock = DockStyle.Fill;
            _gridGroup.BackColor = Color.White;
            _gridGroup.Padding = new Padding(10, 8, 10, 10);
            _grid.Name = "_grid";
            _grid.Dock = DockStyle.Fill;
            _grid.AutoGenerateColumns = false;
            _grid.AllowUserToAddRows = false;
            _grid.AllowUserToDeleteRows = false;
            _grid.AllowUserToResizeRows = false;
            _grid.ReadOnly = true;
            _grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            _grid.MultiSelect = false;
            _grid.RowHeadersVisible = false;
            _grid.BackgroundColor = Color.White;
            _grid.BorderStyle = BorderStyle.FixedSingle;
            _grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            _grid.EnableHeadersVisualStyles = false;
            _grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(238, 241, 245);
            _grid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(30, 30, 30);
            _grid.ColumnHeadersDefaultCellStyle.Font = new Font(_grid.Font, FontStyle.Bold);
            _grid.ColumnHeadersHeight = 32;
            _grid.RowTemplate.Height = 28;
            _grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(0, 120, 215);
            _grid.DefaultCellStyle.SelectionForeColor = Color.White;
            _grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(250, 251, 252);
            _grid.CellFormatting += GridCellFormatting;
            _grid.SelectionChanged += Grid_SelectionChanged;
            _grid.DataError += Grid_DataError;
            _osColumn.Name = "_osColumn"; _osColumn.DataPropertyName = "Id"; _osColumn.HeaderText = "OS"; _osColumn.FillWeight = 55; _osColumn.MinimumWidth = 55; _osColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _osColumn.DefaultCellStyle.NullValue = string.Empty;
            _clienteNomeColumn.Name = "_clienteNomeColumn"; _clienteNomeColumn.DataPropertyName = "ClienteNome"; _clienteNomeColumn.HeaderText = "Cliente"; _clienteNomeColumn.FillWeight = 200; _clienteNomeColumn.MinimumWidth = 70; _clienteNomeColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft; _clienteNomeColumn.DefaultCellStyle.NullValue = string.Empty;
            _aberturaColumn.Name = "_aberturaColumn"; _aberturaColumn.DataPropertyName = "DataAbertura"; _aberturaColumn.HeaderText = "Abertura"; _aberturaColumn.FillWeight = 120; _aberturaColumn.MinimumWidth = 70; _aberturaColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft; _aberturaColumn.DefaultCellStyle.Format = "g"; _aberturaColumn.DefaultCellStyle.NullValue = string.Empty;
            _conclusaoColumn.Name = "_conclusaoColumn"; _conclusaoColumn.DataPropertyName = "DataConclusao"; _conclusaoColumn.HeaderText = "Conclusao"; _conclusaoColumn.FillWeight = 110; _conclusaoColumn.MinimumWidth = 70; _conclusaoColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft; _conclusaoColumn.DefaultCellStyle.NullValue = string.Empty;
            _statusColumn.Name = "_statusColumn"; _statusColumn.DataPropertyName = "Status"; _statusColumn.HeaderText = "Status"; _statusColumn.FillWeight = 95; _statusColumn.MinimumWidth = 70; _statusColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleLeft; _statusColumn.DefaultCellStyle.NullValue = string.Empty;
            _totalColumn.Name = "_totalColumn"; _totalColumn.DataPropertyName = "ValorTotal"; _totalColumn.HeaderText = "Total"; _totalColumn.FillWeight = 95; _totalColumn.MinimumWidth = 70; _totalColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _totalColumn.DefaultCellStyle.Format = "C2"; _totalColumn.DefaultCellStyle.NullValue = string.Empty;
            _versaoColumn.Name = "_versaoColumn"; _versaoColumn.DataPropertyName = "Versao"; _versaoColumn.HeaderText = "Versao"; _versaoColumn.FillWeight = 65; _versaoColumn.MinimumWidth = 65; _versaoColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _versaoColumn.DefaultCellStyle.NullValue = string.Empty;
            _grid.Columns.AddRange(new DataGridViewColumn[] { _osColumn, _clienteNomeColumn, _aberturaColumn, _conclusaoColumn, _statusColumn, _totalColumn, _versaoColumn });
        
            _gridGroup.Controls.Add(_grid);

            _editorRoot.Name = "_editorRoot";
            _editorRoot.Dock = DockStyle.Fill;
            _editorRoot.ColumnCount = 2;
            _editorRoot.RowCount = 1;
            _editorRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42));
            _editorRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58));

            _dadosGroup.Name = "_dadosGroup";
            _dadosGroup.Text = "Dados da ordem";
            _dadosGroup.Dock = DockStyle.Fill;
            _dadosGroup.BackColor = Color.White;
            _dadosGroup.Padding = new Padding(10, 8, 10, 10);
            _dadosPanel.Name = "_dadosPanel";
            _dadosPanel.Dock = DockStyle.Fill;
            _dadosPanel.ColumnCount = 2;
            _dadosPanel.RowCount = 7;
            _dadosPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100));
            _dadosPanel.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            _dadosPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
            _clienteLabel.Name = "_clienteLabel"; _clienteLabel.Text = "Cliente"; _clienteLabel.Dock = DockStyle.Fill; _clienteLabel.TextAlign = ContentAlignment.MiddleLeft; _clienteLabel.Margin = new Padding(3, 3, 6, 3);
            _aberturaLabel.Name = "_aberturaLabel"; _aberturaLabel.Text = "Abertura"; _aberturaLabel.Dock = DockStyle.Fill; _aberturaLabel.TextAlign = ContentAlignment.MiddleLeft; _aberturaLabel.Margin = new Padding(3, 3, 6, 3);
            _statusLabel.Name = "_statusLabel"; _statusLabel.Text = "Status"; _statusLabel.Dock = DockStyle.Fill; _statusLabel.TextAlign = ContentAlignment.MiddleLeft; _statusLabel.Margin = new Padding(3, 3, 6, 3);
            _conclusaoLabel.Name = "_conclusaoLabel"; _conclusaoLabel.Text = "Conclusao"; _conclusaoLabel.Dock = DockStyle.Fill; _conclusaoLabel.TextAlign = ContentAlignment.MiddleLeft; _conclusaoLabel.Margin = new Padding(3, 3, 6, 3);
            _observacaoLabel.Name = "_observacaoLabel"; _observacaoLabel.Text = "Observacao"; _observacaoLabel.Dock = DockStyle.Fill; _observacaoLabel.TextAlign = ContentAlignment.MiddleLeft; _observacaoLabel.Margin = new Padding(3, 3, 6, 3);
            _cliente.Name = "_cliente"; _cliente.Dock = DockStyle.Fill; _cliente.Margin = new Padding(3, 3, 8, 3); _cliente.DropDownStyle = ComboBoxStyle.DropDownList;
            _abertura.Name = "_abertura"; _abertura.Dock = DockStyle.Fill; _abertura.Margin = new Padding(3, 3, 8, 3); _abertura.Format = DateTimePickerFormat.Short;
            _status.Name = "_status"; _status.Dock = DockStyle.Fill; _status.Margin = new Padding(3, 3, 8, 3); _status.DropDownStyle = ComboBoxStyle.DropDownList; _status.SelectedIndexChanged += Status_SelectedIndexChanged;
            _usarConclusao.Name = "_usarConclusao"; _usarConclusao.Text = "Informar conclusao"; _usarConclusao.Dock = DockStyle.Fill; _usarConclusao.CheckedChanged += UsarConclusao_CheckedChanged;
            _conclusao.Name = "_conclusao"; _conclusao.Dock = DockStyle.Fill; _conclusao.Margin = new Padding(3, 3, 8, 3); _conclusao.Format = DateTimePickerFormat.Short; _conclusao.Enabled = false;
            _observacao.Name = "_observacao"; _observacao.Dock = DockStyle.Fill; _observacao.Margin = new Padding(3, 3, 8, 3); _observacao.Multiline = true; _observacao.ScrollBars = ScrollBars.Vertical; _observacao.MaxLength = 2000;
            _salvarButton.Name = "_salvarButton"; _salvarButton.Text = "Salvar OS"; _salvarButton.Width = 110; _salvarButton.Height = 30; _salvarButton.Margin = new Padding(4); _salvarButton.FlatStyle = FlatStyle.System; _salvarButton.UseVisualStyleBackColor = true; _salvarButton.Click += SalvarButton_Click;
            _salvarPanel.Name = "_salvarPanel"; _salvarPanel.Dock = DockStyle.Fill; _salvarPanel.FlowDirection = FlowDirection.RightToLeft; _salvarPanel.WrapContents = false; _salvarPanel.Controls.Add(_salvarButton);
            _dadosPanel.Controls.Add(_clienteLabel, 0, 0); _dadosPanel.Controls.Add(_cliente, 1, 0);
            _dadosPanel.Controls.Add(_aberturaLabel, 0, 1); _dadosPanel.Controls.Add(_abertura, 1, 1);
            _dadosPanel.Controls.Add(_statusLabel, 0, 2); _dadosPanel.Controls.Add(_status, 1, 2);
            _dadosPanel.Controls.Add(_usarConclusao, 1, 3);
            _dadosPanel.Controls.Add(_conclusaoLabel, 0, 4); _dadosPanel.Controls.Add(_conclusao, 1, 4);
            _dadosPanel.Controls.Add(_observacaoLabel, 0, 5); _dadosPanel.Controls.Add(_observacao, 1, 5);
            _dadosPanel.Controls.Add(_salvarPanel, 0, 6); _dadosPanel.SetColumnSpan(_salvarPanel, 2);
        
            _dadosGroup.Controls.Add(_dadosPanel);

            _itensGroup.Name = "_itensGroup";
            _itensGroup.Text = "Itens da ordem";
            _itensGroup.Dock = DockStyle.Fill;
            _itensGroup.BackColor = Color.White;
            _itensGroup.Padding = new Padding(10, 8, 10, 10);
            _itensPanel.Name = "_itensPanel";
            _itensPanel.Dock = DockStyle.Fill;
            _itensPanel.ColumnCount = 1;
            _itensPanel.RowCount = 2;
            _itensPanel.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
            _itensPanel.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            _itensTopo.Name = "_itensTopo"; _itensTopo.Dock = DockStyle.Fill; _itensTopo.ColumnCount = 6; _itensTopo.RowCount = 1;
            _itensTopo.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 64));
            _itensTopo.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _itensTopo.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 42));
            _itensTopo.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 110));
            _itensTopo.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 104));
            _itensTopo.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 104));
            _servicoLabel.Name = "_servicoLabel"; _servicoLabel.Text = "Servico"; _servicoLabel.Dock = DockStyle.Fill; _servicoLabel.TextAlign = ContentAlignment.MiddleLeft; _servicoLabel.Margin = new Padding(3, 3, 6, 3);
            _quantidadeLabel.Name = "_quantidadeLabel"; _quantidadeLabel.Text = "Qtd"; _quantidadeLabel.Dock = DockStyle.Fill; _quantidadeLabel.TextAlign = ContentAlignment.MiddleLeft; _quantidadeLabel.Margin = new Padding(3, 3, 6, 3);
            _servicoItem.Name = "_servicoItem"; _servicoItem.Dock = DockStyle.Fill; _servicoItem.Margin = new Padding(3, 3, 8, 3); _servicoItem.DropDownStyle = ComboBoxStyle.DropDownList;
            _quantidade.Name = "_quantidade"; _quantidade.Dock = DockStyle.Fill; _quantidade.Margin = new Padding(3, 3, 8, 3); _quantidade.DecimalPlaces = 2; _quantidade.Minimum = 1; _quantidade.Maximum = 999; _quantidade.Increment = 1; _quantidade.ThousandsSeparator = true; _quantidade.Value = 1;
            _adicionarItemButton.Name = "_adicionarItemButton"; _adicionarItemButton.Text = "Adicionar"; _adicionarItemButton.Width = 96; _adicionarItemButton.Height = 30; _adicionarItemButton.Margin = new Padding(4); _adicionarItemButton.FlatStyle = FlatStyle.System; _adicionarItemButton.UseVisualStyleBackColor = true; _adicionarItemButton.Click += AdicionarItemButton_Click;
            _removerItemButton.Name = "_removerItemButton"; _removerItemButton.Text = "Remover"; _removerItemButton.Width = 96; _removerItemButton.Height = 30; _removerItemButton.Margin = new Padding(4); _removerItemButton.FlatStyle = FlatStyle.System; _removerItemButton.UseVisualStyleBackColor = true; _removerItemButton.Click += RemoverItemButton_Click;
            _itensTopo.Controls.Add(_servicoLabel, 0, 0); _itensTopo.Controls.Add(_servicoItem, 1, 0); _itensTopo.Controls.Add(_quantidadeLabel, 2, 0); _itensTopo.Controls.Add(_quantidade, 3, 0); _itensTopo.Controls.Add(_adicionarItemButton, 4, 0); _itensTopo.Controls.Add(_removerItemButton, 5, 0);
            _itensGrid.Name = "_itensGrid"; _itensGrid.Dock = DockStyle.Fill; _itensGrid.AutoGenerateColumns = false; _itensGrid.AllowUserToAddRows = false; _itensGrid.AllowUserToDeleteRows = false; _itensGrid.AllowUserToResizeRows = false; _itensGrid.ReadOnly = true; _itensGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect; _itensGrid.MultiSelect = false; _itensGrid.RowHeadersVisible = false; _itensGrid.BackgroundColor = Color.White; _itensGrid.BorderStyle = BorderStyle.FixedSingle; _itensGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill; _itensGrid.EnableHeadersVisualStyles = false; _itensGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(238, 241, 245); _itensGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(30, 30, 30); _itensGrid.ColumnHeadersDefaultCellStyle.Font = new Font(_itensGrid.Font, FontStyle.Bold); _itensGrid.ColumnHeadersHeight = 32; _itensGrid.RowTemplate.Height = 28; _itensGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(0, 120, 215); _itensGrid.DefaultCellStyle.SelectionForeColor = Color.White; _itensGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(250, 251, 252); _itensGrid.DataError += Grid_DataError;
            _itemServicoColumn.Name = "_itemServicoColumn"; _itemServicoColumn.DataPropertyName = "ServicoId"; _itemServicoColumn.HeaderText = "Servico"; _itemServicoColumn.FillWeight = 85; _itemServicoColumn.MinimumWidth = 70; _itemServicoColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _itemServicoColumn.DefaultCellStyle.NullValue = string.Empty; _itemQuantidadeColumn.Name = "_itemQuantidadeColumn"; _itemQuantidadeColumn.DataPropertyName = "Quantidade"; _itemQuantidadeColumn.HeaderText = "Qtd"; _itemQuantidadeColumn.FillWeight = 80; _itemQuantidadeColumn.MinimumWidth = 70; _itemQuantidadeColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _itemQuantidadeColumn.DefaultCellStyle.Format = "N2"; _itemQuantidadeColumn.DefaultCellStyle.NullValue = string.Empty; _itemValorUnitarioColumn.Name = "_itemValorUnitarioColumn"; _itemValorUnitarioColumn.DataPropertyName = "ValorUnitario"; _itemValorUnitarioColumn.HeaderText = "Valor unitario"; _itemValorUnitarioColumn.FillWeight = 110; _itemValorUnitarioColumn.MinimumWidth = 70; _itemValorUnitarioColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _itemValorUnitarioColumn.DefaultCellStyle.Format = "C2"; _itemValorUnitarioColumn.DefaultCellStyle.NullValue = string.Empty; _itemImpostoColumn.Name = "_itemImpostoColumn"; _itemImpostoColumn.DataPropertyName = "PercentualImpostoAplicado"; _itemImpostoColumn.HeaderText = "Imposto %"; _itemImpostoColumn.FillWeight = 95; _itemImpostoColumn.MinimumWidth = 70; _itemImpostoColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _itemImpostoColumn.DefaultCellStyle.Format = "N2"; _itemImpostoColumn.DefaultCellStyle.NullValue = string.Empty; _itemTotalColumn.Name = "_itemTotalColumn"; _itemTotalColumn.DataPropertyName = "ValorTotalItem"; _itemTotalColumn.HeaderText = "Total"; _itemTotalColumn.FillWeight = 110; _itemTotalColumn.MinimumWidth = 70; _itemTotalColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight; _itemTotalColumn.DefaultCellStyle.Format = "C2"; _itemTotalColumn.DefaultCellStyle.NullValue = string.Empty;
            _itensGrid.Columns.AddRange(new DataGridViewColumn[] { _itemServicoColumn, _itemQuantidadeColumn, _itemValorUnitarioColumn, _itemImpostoColumn, _itemTotalColumn });
            _itensPanel.Controls.Add(_itensTopo, 0, 0); _itensPanel.Controls.Add(_itensGrid, 0, 1);
        
            _itensGroup.Controls.Add(_itensPanel);

            _editorRoot.Controls.Add(_dadosGroup, 0, 0);
            _editorRoot.Controls.Add(_itensGroup, 1, 0);
            _root.Controls.Add(_filtrosGroup, 0, 0);
            _root.Controls.Add(_gridGroup, 0, 1);
            _root.Controls.Add(_editorRoot, 0, 2);
            Controls.Add(_root);
            ((ISupportInitialize)_grid).EndInit();
            ((ISupportInitialize)_quantidade).EndInit();
            ((ISupportInitialize)_itensGrid).EndInit();
            ResumeLayout(false);
        }

    }
}
