using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace GestaoOS.WinForms
{
    public partial class ServicoForm
    {
        private IContainer components = null;
        private TableLayoutPanel _root;
        private GroupBox _filtrosGroup;
        private TableLayoutPanel _filtrosLayout;
        private TableLayoutPanel _pagerLayout;
        private GroupBox _editorGroup;
        private TableLayoutPanel _editorLayout;
        private FlowLayoutPanel _actionsPanel;
        private Label _filtroNomeLabel;
        private Label _filtroAtivoLabel;
        private Label _nomeLabel;
        private Label _valorBaseLabel;
        private Label _percentualImpostoLabel;
        private Button _pesquisarButton;
        private Button _novoButton;
        private Button _anteriorButton;
        private Button _proximaButton;
        private Button _salvarButton;
        private TextBox _filtroNome;
        private ComboBox _filtroAtivo;
        private DataGridView _grid;
        private TextBox _nome;
        private NumericUpDown _valorBase;
        private NumericUpDown _percentualImposto;
        private CheckBox _ativo;
        private Label _paginaLabel;
        private DataGridViewTextBoxColumn _idColumn;
        private DataGridViewTextBoxColumn _nomeColumn;
        private DataGridViewTextBoxColumn _valorBaseColumn;
        private DataGridViewTextBoxColumn _percentualImpostoColumn;
        private DataGridViewCheckBoxColumn _ativoColumn;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new Container();
            _root = new TableLayoutPanel();
            _filtrosGroup = new GroupBox();
            _filtrosLayout = new TableLayoutPanel();
            _pagerLayout = new TableLayoutPanel();
            _editorGroup = new GroupBox();
            _editorLayout = new TableLayoutPanel();
            _actionsPanel = new FlowLayoutPanel();
            _filtroNomeLabel = new Label();
            _filtroAtivoLabel = new Label();
            _nomeLabel = new Label();
            _valorBaseLabel = new Label();
            _percentualImpostoLabel = new Label();
            _pesquisarButton = new Button();
            _novoButton = new Button();
            _anteriorButton = new Button();
            _proximaButton = new Button();
            _salvarButton = new Button();
            _filtroNome = new TextBox();
            _filtroAtivo = new ComboBox();
            _grid = new DataGridView();
            _nome = new TextBox();
            _valorBase = new NumericUpDown();
            _percentualImposto = new NumericUpDown();
            _ativo = new CheckBox();
            _paginaLabel = new Label();
            _idColumn = new DataGridViewTextBoxColumn();
            _nomeColumn = new DataGridViewTextBoxColumn();
            _valorBaseColumn = new DataGridViewTextBoxColumn();
            _percentualImpostoColumn = new DataGridViewTextBoxColumn();
            _ativoColumn = new DataGridViewCheckBoxColumn();
            ((ISupportInitialize)_grid).BeginInit();
            ((ISupportInitialize)_valorBase).BeginInit();
            ((ISupportInitialize)_percentualImposto).BeginInit();
            SuspendLayout();

            Text = "Servicos";
            StartPosition = FormStartPosition.CenterParent;
            Font = new Font("Segoe UI", 9F, FontStyle.Regular, GraphicsUnit.Point);
            BackColor = Color.FromArgb(245, 246, 248);
            Size = new Size(980, 660);
            MinimumSize = new Size(880, 580);
            Padding = new Padding(10);

            _root.Name = "_root";
            _root.Dock = DockStyle.Fill;
            _root.ColumnCount = 1;
            _root.RowCount = 3;
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 122));
            _root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            _root.RowStyles.Add(new RowStyle(SizeType.Absolute, 185));

            _filtrosGroup.Name = "_filtrosGroup";
            _filtrosGroup.Text = "Pesquisa";
            _filtrosGroup.Dock = DockStyle.Fill;
            _filtrosGroup.BackColor = Color.White;
            _filtrosGroup.Padding = new Padding(10, 8, 10, 10);
            _filtrosLayout.Name = "_filtrosLayout";
            _filtrosLayout.Dock = DockStyle.Fill;
            _filtrosLayout.ColumnCount = 6;
            _filtrosLayout.RowCount = 2;
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 60));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 55));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 108));
            _filtrosLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100));
            _filtrosLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38));
            _filtrosLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));
            _filtroNomeLabel.Name = "_filtroNomeLabel";
            _filtroNomeLabel.Text = "Nome";
            _filtroNomeLabel.Dock = DockStyle.Fill;
            _filtroNomeLabel.TextAlign = ContentAlignment.MiddleLeft;
            _filtroNomeLabel.Margin = new Padding(3, 3, 6, 3);
            _filtroAtivoLabel.Name = "_filtroAtivoLabel";
            _filtroAtivoLabel.Text = "Ativo";
            _filtroAtivoLabel.Dock = DockStyle.Fill;
            _filtroAtivoLabel.TextAlign = ContentAlignment.MiddleLeft;
            _filtroAtivoLabel.Margin = new Padding(3, 3, 6, 3);
            _filtroNome.Name = "_filtroNome";
            _filtroNome.Dock = DockStyle.Fill;
            _filtroNome.Margin = new Padding(3, 3, 8, 3);
            _filtroNome.MaxLength = 150;
            _filtroAtivo.Name = "_filtroAtivo";
            _filtroAtivo.Dock = DockStyle.Fill;
            _filtroAtivo.Margin = new Padding(3, 3, 8, 3);
            _filtroAtivo.DropDownStyle = ComboBoxStyle.DropDownList;
            _filtroAtivo.Items.AddRange(new object[] { "Todos", "Ativos", "Inativos" });
            _filtroAtivo.SelectedIndex = 0;
            _pesquisarButton.Name = "_pesquisarButton";
            _pesquisarButton.Text = "Pesquisar";
            _pesquisarButton.Width = 96;
            _pesquisarButton.Height = 30;
            _pesquisarButton.Margin = new Padding(4);
            _pesquisarButton.FlatStyle = FlatStyle.System;
            _pesquisarButton.UseVisualStyleBackColor = true;
            _pesquisarButton.Click += PesquisarButton_Click;
            _novoButton.Name = "_novoButton";
            _novoButton.Text = "Novo";
            _novoButton.Width = 96;
            _novoButton.Height = 30;
            _novoButton.Margin = new Padding(4);
            _novoButton.FlatStyle = FlatStyle.System;
            _novoButton.UseVisualStyleBackColor = true;
            _novoButton.Click += NovoButton_Click;

            _pagerLayout.Name = "_pagerLayout";
            _pagerLayout.Dock = DockStyle.Fill;
            _pagerLayout.ColumnCount = 3;
            _pagerLayout.RowCount = 1;
            _pagerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            _pagerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96));
            _pagerLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 96));
            _paginaLabel.Name = "_paginaLabel";
            _paginaLabel.Dock = DockStyle.Fill;
            _paginaLabel.TextAlign = ContentAlignment.MiddleRight;
            _anteriorButton.Name = "_anteriorButton";
            _anteriorButton.Text = "Anterior";
            _anteriorButton.Width = 96;
            _anteriorButton.Height = 30;
            _anteriorButton.Margin = new Padding(4, 2, 4, 8);
            _anteriorButton.FlatStyle = FlatStyle.System;
            _anteriorButton.UseVisualStyleBackColor = true;
            _anteriorButton.Click += AnteriorButton_Click;
            _proximaButton.Name = "_proximaButton";
            _proximaButton.Text = "Proxima";
            _proximaButton.Width = 96;
            _proximaButton.Height = 30;
            _proximaButton.Margin = new Padding(4, 2, 4, 8);
            _proximaButton.FlatStyle = FlatStyle.System;
            _proximaButton.UseVisualStyleBackColor = true;
            _proximaButton.Click += ProximaButton_Click;
            _pagerLayout.Controls.Add(_paginaLabel, 0, 0);
            _pagerLayout.Controls.Add(_anteriorButton, 1, 0);
            _pagerLayout.Controls.Add(_proximaButton, 2, 0);

            _filtrosLayout.Controls.Add(_filtroNomeLabel, 0, 0);
            _filtrosLayout.Controls.Add(_filtroNome, 1, 0);
            _filtrosLayout.Controls.Add(_filtroAtivoLabel, 2, 0);
            _filtrosLayout.Controls.Add(_filtroAtivo, 3, 0);
            _filtrosLayout.Controls.Add(_pesquisarButton, 4, 0);
            _filtrosLayout.Controls.Add(_novoButton, 5, 0);
            _filtrosLayout.Controls.Add(_pagerLayout, 0, 1);
            _filtrosLayout.SetColumnSpan(_pagerLayout, 6);
            _filtrosGroup.Controls.Add(_filtrosLayout);

            _grid.Dock = DockStyle.Fill;
            _grid.AutoGenerateColumns = false;
            _grid.AllowUserToAddRows = false;
            _grid.AllowUserToDeleteRows = false;
            _grid.AllowUserToResizeRows = false;
            _grid.ReadOnly = true;
            _grid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            _grid.MultiSelect = false;
            _grid.RowHeadersVisible = false;
            _grid.BackgroundColor = Color.White;
            _grid.BorderStyle = BorderStyle.FixedSingle;
            _grid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            _grid.EnableHeadersVisualStyles = false;
            _grid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(238, 241, 245);
            _grid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(30, 30, 30);
            _grid.ColumnHeadersDefaultCellStyle.Font = new Font(_grid.Font, FontStyle.Bold);
            _grid.ColumnHeadersHeight = 32;
            _grid.RowTemplate.Height = 28;
            _grid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(0, 120, 215);
            _grid.DefaultCellStyle.SelectionForeColor = Color.White;
            _grid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(250, 251, 252);
            _grid.Name = "_grid";
            _grid.SelectionChanged += Grid_SelectionChanged;
            _grid.DataError += Grid_DataError;
            _idColumn.Name = "_idColumn";
            _idColumn.DataPropertyName = "Id";
            _idColumn.HeaderText = "Id";
            _idColumn.FillWeight = 60;
            _idColumn.MinimumWidth = 60;
            _idColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            _nomeColumn.Name = "_nomeColumn";
            _nomeColumn.DataPropertyName = "Nome";
            _nomeColumn.HeaderText = "Nome";
            _nomeColumn.FillWeight = 220;
            _nomeColumn.MinimumWidth = 70;
            _valorBaseColumn.Name = "_valorBaseColumn";
            _valorBaseColumn.DataPropertyName = "ValorBase";
            _valorBaseColumn.HeaderText = "Valor base";
            _valorBaseColumn.FillWeight = 110;
            _valorBaseColumn.MinimumWidth = 70;
            _valorBaseColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            _valorBaseColumn.DefaultCellStyle.Format = "C2";
            _percentualImpostoColumn.Name = "_percentualImpostoColumn";
            _percentualImpostoColumn.DataPropertyName = "PercentualImposto";
            _percentualImpostoColumn.HeaderText = "Imposto %";
            _percentualImpostoColumn.FillWeight = 95;
            _percentualImpostoColumn.MinimumWidth = 70;
            _percentualImpostoColumn.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            _percentualImpostoColumn.DefaultCellStyle.Format = "N2";
            _ativoColumn.Name = "_ativoColumn";
            _ativoColumn.DataPropertyName = "Ativo";
            _ativoColumn.HeaderText = "Ativo";
            _ativoColumn.FillWeight = 70;
            _ativoColumn.MinimumWidth = 60;
            _grid.Columns.AddRange(new DataGridViewColumn[] { _idColumn, _nomeColumn, _valorBaseColumn, _percentualImpostoColumn, _ativoColumn });

            _editorGroup.Name = "_editorGroup";
            _editorGroup.Text = "Dados do servico";
            _editorGroup.Dock = DockStyle.Fill;
            _editorGroup.BackColor = Color.White;
            _editorGroup.Padding = new Padding(10, 8, 10, 10);
            _editorLayout.Name = "_editorLayout";
            _editorLayout.Dock = DockStyle.Fill;
            _editorLayout.ColumnCount = 4;
            _editorLayout.RowCount = 3;
            _editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100));
            _editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
            _editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120));
            _editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
            _editorLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _editorLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 34));
            _editorLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            _nomeLabel.Name = "_nomeLabel";
            _nomeLabel.Text = "Nome";
            _nomeLabel.Dock = DockStyle.Fill;
            _nomeLabel.TextAlign = ContentAlignment.MiddleLeft;
            _nomeLabel.Margin = new Padding(3, 3, 6, 3);
            _valorBaseLabel.Name = "_valorBaseLabel";
            _valorBaseLabel.Text = "Valor base";
            _valorBaseLabel.Dock = DockStyle.Fill;
            _valorBaseLabel.TextAlign = ContentAlignment.MiddleLeft;
            _valorBaseLabel.Margin = new Padding(3, 3, 6, 3);
            _percentualImpostoLabel.Name = "_percentualImpostoLabel";
            _percentualImpostoLabel.Text = "Imposto %";
            _percentualImpostoLabel.Dock = DockStyle.Fill;
            _percentualImpostoLabel.TextAlign = ContentAlignment.MiddleLeft;
            _percentualImpostoLabel.Margin = new Padding(3, 3, 6, 3);
            _nome.Name = "_nome";
            _nome.Dock = DockStyle.Fill;
            _nome.Margin = new Padding(3, 3, 8, 3);
            _nome.MaxLength = 150;
            _valorBase.Name = "_valorBase";
            _valorBase.Dock = DockStyle.Fill;
            _valorBase.Margin = new Padding(3, 3, 8, 3);
            _valorBase.DecimalPlaces = 2;
            _valorBase.Maximum = 9999999;
            _valorBase.Minimum = 0;
            _valorBase.Increment = 10;
            _valorBase.ThousandsSeparator = true;
            _percentualImposto.Name = "_percentualImposto";
            _percentualImposto.Dock = DockStyle.Fill;
            _percentualImposto.Margin = new Padding(3, 3, 8, 3);
            _percentualImposto.DecimalPlaces = 2;
            _percentualImposto.Maximum = 100;
            _percentualImposto.Minimum = 0;
            _percentualImposto.Increment = 0.5m;
            _ativo.Name = "_ativo";
            _ativo.Text = "Ativo";
            _ativo.Checked = true;
            _ativo.Dock = DockStyle.Fill;
            _salvarButton.Name = "_salvarButton";
            _salvarButton.Text = "Salvar";
            _salvarButton.Width = 96;
            _salvarButton.Height = 30;
            _salvarButton.Margin = new Padding(4);
            _salvarButton.FlatStyle = FlatStyle.System;
            _salvarButton.UseVisualStyleBackColor = true;
            _salvarButton.Click += SalvarButton_Click;
            _actionsPanel.Name = "_actionsPanel";
            _actionsPanel.Dock = DockStyle.Fill;
            _actionsPanel.FlowDirection = FlowDirection.RightToLeft;
            _actionsPanel.WrapContents = false;
            _actionsPanel.Controls.Add(_salvarButton);
            _editorLayout.Controls.Add(_nomeLabel, 0, 0);
            _editorLayout.Controls.Add(_nome, 1, 0);
            _editorLayout.Controls.Add(_valorBaseLabel, 2, 0);
            _editorLayout.Controls.Add(_valorBase, 3, 0);
            _editorLayout.Controls.Add(_percentualImpostoLabel, 0, 1);
            _editorLayout.Controls.Add(_percentualImposto, 1, 1);
            _editorLayout.Controls.Add(_ativo, 2, 1);
            _editorLayout.Controls.Add(_actionsPanel, 0, 2);
            _editorLayout.SetColumnSpan(_actionsPanel, 4);
            _editorGroup.Controls.Add(_editorLayout);

            _root.Controls.Add(_filtrosGroup, 0, 0);
            _root.Controls.Add(_grid, 0, 1);
            _root.Controls.Add(_editorGroup, 0, 2);
            Controls.Add(_root);
            ((ISupportInitialize)_grid).EndInit();
            ((ISupportInitialize)_valorBase).EndInit();
            ((ISupportInitialize)_percentualImposto).EndInit();
            ResumeLayout(false);
        }
    }
}
